name: productos_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^6.0.0
  image_picker: ^0.8.3+3
  photo_view: ^0.14.0
  flutter_reaction_button: ^1.0.8
  share: ^2.0.4
  flutter_secure_storage: ^4.2.1
  url_launcher: ^6.0.10
  font_awesome_flutter: ^9.1.0
  shared_preferences: ^2.0.6
  firebase_database: ^8.0.0
  firebase_storage: ^10.0.3
  intl: ^0.17.0
  firebase_core: ^1.6.0
  cloud_firestore: ^2.5.3
  open_mail_app: ^0.3.0

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  fonts:
    - family: MeriendaOne
      fonts:
        - asset: fonts/MeriendaOne-Regular.ttf
    - family: RacingSansOne
      fonts:
        - asset: fonts/RacingSansOne-Regular.ttf


  uses-material-design: true

  assets:
    - assets/
